services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  adminer:
    build: ./requirements/adminer
    container_name: adminer
    restart: always
    ports:
      - "80:80"
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sben-tay/data
